'use client'

import { useEffect, useState } from 'react'
import { ChevronDown, ExternalLink, Play, Search, ShieldCheck, X } from 'lucide-react'

type Video = { id: string; title: string; channel: string; views?: string; time?: string; duration?: number; image: string; streamUrl?: string | null; embedUrl?: string; sourceName?: string; sourceUrl?: string }
const fmt = (n?: number) => n ? `${Math.floor(n / 60)}:${String(n % 60).padStart(2, '0')}` : ''

export default function CtubeApp() {
  const [query, setQuery] = useState(''), [videos, setVideos] = useState<Video[]>([]), [selected, setSelected] = useState<Video | null>(null), [loading, setLoading] = useState(false), [loadingMore, setLoadingMore] = useState(false), [page, setPage] = useState(1), [hasMore, setHasMore] = useState(true), [error, setError] = useState(''), [sourceOpen, setSourceOpen] = useState(false)
  async function search(e?: React.FormEvent) { e?.preventDefault(); if (!query.trim()) return; setLoading(true); setError(''); try { const r = await fetch(`/api/videos?q=${encodeURIComponent(query.trim())}`, { cache: 'no-store' }); const d = await r.json(); if (!r.ok) throw new Error(d.error); setVideos(d.videos ?? []); setPage(1); setHasMore(Boolean(d.hasMore ?? (d.videos?.length > 0))); setSelected(null) } catch (e) { setError(e instanceof Error ? e.message : 'Não foi possível pesquisar agora.') } finally { setLoading(false) } }
  async function loadMore() { if (!query.trim() || loadingMore || !hasMore) return; setLoadingMore(true); try { const r = await fetch(`/api/videos?q=${encodeURIComponent(query.trim())}&page=${page + 1}`, { cache: 'no-store' }); const d = await r.json(); if (!r.ok) throw new Error(d.error); setVideos(current => { const ids = new Set(current.map(item => item.id)); return [...current, ...(d.videos ?? []).filter((item: Video) => !ids.has(item.id))] }); setPage(value => value + 1); setHasMore(Boolean(d.hasMore ?? d.videos?.length)) } catch (e) { setError(e instanceof Error ? e.message : 'Não foi possível carregar mais resultados.') } finally { setLoadingMore(false) } }
  async function openVideo(v: Video) { setSelected({ ...v, title: v.title || 'Carregando vídeo…' }); setError(''); if (v.streamUrl !== undefined || v.embedUrl) return; try { const r = await fetch(`/api/videos?id=${encodeURIComponent(v.id)}`, { cache: 'no-store' }); const d = await r.json(); if (!r.ok) throw new Error(d.error); setSelected({ ...v, ...d.video, sourceName: d.source, sourceUrl: d.video.sourceUrl ?? `https://www.youtube.com/watch?v=${v.id}` }); window.history.replaceState(null, '', `/?v=${v.id}`) } catch (e) { setError(e instanceof Error ? e.message : 'Não foi possível carregar este vídeo.') } }
  useEffect(() => { const id = new URLSearchParams(location.search).get('v'); if (id) openVideo({ id, title: '', channel: '', image: `https://i.ytimg.com/vi/${id}/hqdefault.jpg` }) }, [])
  return <main className="ctube-results-scroll min-h-screen bg-background text-foreground"><header className="sticky top-0 z-30 flex min-h-20 items-center justify-between gap-4 border-b border-border bg-background/95 px-4 backdrop-blur lg:px-8"><div className="flex items-center gap-3" aria-label="CTUBE"><span className="flex size-11 items-center justify-center rounded-xl bg-primary text-primary-foreground shadow-sm md:size-14"><Play className="size-6 fill-current md:size-8" /></span><span className="text-3xl font-black tracking-tight md:text-4xl">CTUBE</span></div><form onSubmit={search} className="hidden w-full max-w-xl md:flex"><div className="flex h-11 w-full items-center gap-3 rounded-full border border-border bg-muted/60 px-4 focus-within:border-primary"><Search className="size-4 text-muted-foreground" /><input aria-label="Pesquisar" value={query} onChange={e => setQuery(e.target.value)} placeholder="Pesquisar no CTUBE" className="w-full bg-transparent text-sm outline-none" />{query && <button type="button" onClick={() => setQuery('')} aria-label="Limpar busca"><X className="size-4" /></button>}</div></form><div className="flex items-center gap-2 rounded-full bg-primary/10 px-3 py-2 text-xs font-semibold text-primary"><ShieldCheck className="size-4" />Sem anúncios</div></header><div className="flex"><aside className="hidden min-h-[calc(100vh-5rem)] w-20 shrink-0 flex-col items-center gap-7 border-r border-border bg-muted/20 py-7 text-[11px] text-muted-foreground lg:flex"><Side label="Início" icon="⌂" /><Side label="Inscrições" icon="◔" /><Side label="Histórico" icon="↶" /><Side label="Playlists" icon="▣" /><Side label="Configurações" icon="☷" /></aside><section className="mx-auto w-full max-w-[1500px] px-4 py-6 lg:px-8"><form onSubmit={search} className="mb-6 flex gap-2 md:hidden"><input aria-label="Pesquisar vídeos" value={query} onChange={e => setQuery(e.target.value)} placeholder="Pesquisar vídeos" className="min-w-0 flex-1 rounded-full border border-border bg-card px-4 py-3 text-sm outline-none focus:border-primary" /><button className="rounded-full bg-primary px-5 text-sm font-semibold text-primary-foreground">Buscar</button></form>{error && <div className="mb-5 rounded-xl border border-destructive/30 bg-destructive/10 p-4 text-sm">{error}</div>}{loading ? <div className="p-20 text-center text-muted-foreground">Pesquisando vídeos…</div> : selected ? <Player selected={selected} sourceOpen={sourceOpen} setSourceOpen={setSourceOpen} /> : <Results videos={videos} onSelect={openVideo} query={query} onLoadMore={loadMore} loadingMore={loadingMore} hasMore={hasMore} />}</section></div></main>
}
function Side({ label, icon }: { label: string; icon: string }) { return <button className="flex flex-col items-center gap-2 hover:text-primary"><span className="text-2xl">{icon}</span>{label}</button> }
function Results({ videos, onSelect, query, onLoadMore, loadingMore, hasMore }: { videos: Video[]; onSelect: (v: Video) => void; query: string; onLoadMore: () => void; loadingMore: boolean; hasMore: boolean }) { return <div><div className="mb-5 flex items-center gap-3"><Search className="size-6 text-primary" /><h1 className="text-2xl font-semibold">{query ? `Resultados para “${query}”` : 'Descubra vídeos'}</h1></div>{videos.length ? <div className="grid grid-cols-1 gap-x-5 gap-y-8 sm:grid-cols-2 xl:grid-cols-4">{videos.map(v => <article key={v.id} className="group cursor-pointer" onClick={() => onSelect(v)}><div className="relative aspect-video overflow-hidden rounded-xl bg-muted"><img src={v.image} alt="" className="size-full object-cover transition group-hover:scale-105" />{v.duration ? <span className="absolute bottom-2 right-2 rounded bg-foreground/85 px-1.5 py-0.5 text-xs text-background">{fmt(v.duration)}</span> : null}</div><h2 className="mt-3 line-clamp-2 font-medium leading-5">{v.title}</h2><p className="mt-1 text-sm text-muted-foreground">{v.channel}</p><p className="text-xs text-muted-foreground">{v.views}{v.time && ` · ${v.time}`}</p></article>)}</div> : <div className="rounded-2xl border border-dashed border-border p-16 text-center text-muted-foreground">Pesquise por músicas, canais ou assuntos para começar.</div>}{videos.length > 0 && <div className="mt-8 flex justify-center"><button type="button" onClick={onLoadMore} disabled={loadingMore || !hasMore} className="rounded-full border border-border bg-card px-6 py-3 text-sm font-semibold shadow-sm disabled:cursor-not-allowed disabled:opacity-50">{loadingMore ? 'Carregando mais…' : hasMore ? 'Carregar mais resultados' : 'Fim dos resultados'}</button></div>}</div> }
function Player({ selected, sourceOpen, setSourceOpen }: { selected: Video; sourceOpen: boolean; setSourceOpen: (v: boolean) => void }) { return <div className="mx-auto max-w-5xl"><div className="relative aspect-video overflow-hidden rounded-xl bg-black">{selected.streamUrl ? <video src={selected.streamUrl} poster={selected.image} controls autoPlay className="size-full" /> : selected.embedUrl ? <iframe src={selected.embedUrl} title="Reprodutor CTUBE" allow="autoplay; encrypted-media; picture-in-picture" allowFullScreen className="size-full" /> : <div className="flex size-full items-center justify-center"><img src={selected.image} alt="" className="absolute size-full object-cover opacity-40" /><Play className="relative size-14 text-primary-foreground" /></div>}</div><div className="mt-4 rounded-xl border border-border bg-card p-5"><h1 className="text-xl font-semibold">{selected.title || 'Vídeo'}</h1><p className="mt-2 text-sm text-muted-foreground">{selected.channel}{selected.views && ` · ${selected.views} visualizações`}</p><div className="mt-4 border-t border-border pt-3"><button onClick={() => setSourceOpen(!sourceOpen)} className="flex items-center gap-2 text-sm text-muted-foreground">Detalhes da fonte <ChevronDown className={`size-4 transition ${sourceOpen ? 'rotate-180' : ''}`} /></button>{sourceOpen && <div className="mt-3 space-y-2 text-sm text-muted-foreground"><p>Conteúdo obtido por uma fonte compatível do CTUBE.</p>{selected.sourceUrl && <a href={selected.sourceUrl} target="_blank" rel="noreferrer" className="flex items-center gap-2 text-primary">Abrir página original <ExternalLink className="size-4" /></a>}</div>}</div></div></div> }
